apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: ssh
    enviroment: production
    version: v1
  name: ssh
spec:
  replicas: 1
  selector:
    app: ssh
    version: v1
  template:
    metadata:
      labels:
        app: ssh
        enviroment: production
        version: v1
    spec:
      containers:
      - image: bborbe/ssh:latest
        name: ssh
        ports:
        - containerPort: 22
          name: ssh
        resources:
          limits:
            cpu: 1000m
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 10Mi
