apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: confluence
    enviroment: production
    version: v1
  name: confluence-postgres
spec:
  replicas: 1
  selector:
    app: confluence
    role: postgres
    version: v1
  template:
    metadata:
      labels:
        app: confluence
        enviroment: production
        role: postgres
        version: v1
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: 9N6pbevJuiVO
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_USER
          value: confluence
        - name: POSTGRES_DB
          value: confluence
        image: postgres
        name: confluence-postgres
        ports:
        - containerPort: 5432
          name: postgres
        resources:
          limits:
            cpu: 1000m
            memory: 200Mi
          requests:
            cpu: 250m
            memory: 50Mi
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: confluence-postgres
      volumes:
      - name: confluence-postgres
        persistentVolumeClaim:
          claimName: confluence-postgres
