apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: confluence
    enviroment: production
  name: confluence-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1500Mi
