apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: confluence
    enviroment: production
  name: confluence-postgres
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 500Mi
  nfs:
    path: /data/confluence-postgres
    server: 172.16.30.9
