apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  labels:
    app: nfs
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.178.106
    path: /mnt/storage/kubernetes/test
