apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  labels:
    app: nfs
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.103.0.117
    path: "/"
