apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  labels:
    app: nfs
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.6.0.16
    path: /mnt/storage/kubernetes/test
