kind: Service
apiVersion: v1
metadata:
  name: nfs-web
  labels:
    app: nfs
spec:
  ports:
  - port: 80
  selector:
    role: web-frontend
  externalIPs:
  - 172.16.20.0.20
  - 172.16.20.0.21
  - 172.16.20.0.22
