kind: Service
apiVersion: v1
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  externalIPs:
  externalIPs:
  - 172.16.30.20
  - 172.16.30.21
  - 172.16.30.22
