apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: bind
    enviroment: production
    version: v1
  name: bind
spec:
  replicas: 1
  selector:
    app: bind
    version: v1
  template:
    metadata:
      labels:
        app: bind
        enviroment: production
        version: v1
    spec:
      containers:
      - image: bborbe/bind:latest
        name: bind
        ports:
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 25Mi
        volumeMounts:
        - mountPath: /etc/bind
          name: bind
      volumes:
      - name: bind
        persistentVolumeClaim:
          claimName: bind
