apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: bind
    enviroment: production
  name: bind
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
