apiVersion: v1
kind: Service
metadata:
  labels:
    app: bind
    enviroment: production
  name: bind
spec:
  ports:
  - name: dns-udp
    nodePort: 30053
    port: 53
    protocol: UDP
  - name: dns-tcp
    nodePort: 30054
    port: 53
    protocol: TCP
  selector:
    app: bind
  type: NodePort
