apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: bind
    enviroment: production
  name: bind
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Mi
  nfs:
    path: /data/bind
    server: 172.16.30.9
