apiVersion: v1
kind: Service
metadata:
  labels:
    app: elastickube
    enviroment: production
    name: elastickube-mongo
  name: elastickube-mongo
  namespace: kube-system
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    name: elastickube-mongo
