apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-busybox
  labels:
    app: nfs
    enviroment: development
spec:
  replicas: 2
  selector:
    app: nfs
    role: busybox
  template:
    metadata:
      labels:
        app: nfs
        enviroment: development
        role: busybox
    spec:
      containers:
      - image: busybox
        command:
          - sh
          - -c
          - 'while true; do date > /mnt/index.html; hostname >> /mnt/index.html; sleep 10; sleep $(($RANDOM % 5 + 5)); done'
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
          # name must match the volume name below
          - name: nfs
            mountPath: "/mnt"
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
