apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: nfs
    enviroment: development
  name: nfs
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Mi
  nfs:
    path: /data/nfs
    server: 172.16.30.9
