apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
  labels:
    app: nfs
    enviroment: development
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Mi
