apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: nfs
    enviroment: development
  name: nfs-busybox
spec:
  replicas: 2
  selector:
    app: nfs
    role: busybox
  template:
    metadata:
      labels:
        app: nfs
        enviroment: development
        role: busybox
    spec:
      containers:
      - command:
        - sh
        - -c
        - while true; do date > /mnt/index.html; hostname >> /mnt/index.html; sleep
          10; sleep $(($RANDOM % 5 + 5)); done
        image: busybox
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /mnt
          name: nfs
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
