apiVersion: v1
kind: Service
metadata:
  name: nfs-web
  labels:
    app: nfs
    enviroment: development
spec:
  type: NodePort
  selector:
    role: web-frontend
  ports:
    - port: 8080
      nodePort: 30082
