apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: nfs
    enviroment: development
  name: nfs-web
spec:
  replicas: 2
  selector:
    app: nfs
    role: web
  template:
    metadata:
      labels:
        app: nfs
        enviroment: development
        role: web
    spec:
      containers:
      - image: nginx
        name: nfs
        ports:
        - containerPort: 80
          name: nfs-web
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nfs
          readOnly: true
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
