apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: nfs
    enviroment: development
    version: v1
  name: nfs-web
spec:
  replicas: 2
  selector:
    app: nfs
    role: web
    version: v1
  template:
    metadata:
      labels:
        app: nfs
        enviroment: development
        role: web
        version: v1
    spec:
      containers:
      - image: nginx
        name: nfs
        ports:
        - containerPort: 80
          name: nfs-web
        resources:
          limits:
            cpu: 250m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nfs
          readOnly: true
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
