apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  labels:
    app: nfs
    enviroment: development
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.16.30.9
    path: /data/nfs
