apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-web
  labels:
    app: nfs
    enviroment: development
spec:
  replicas: 2
  selector:
    app: nfs
  template:
    metadata:
      labels:
        app: nfs
        enviroment: development
    spec:
      containers:
      - name: web
        image: nginx
        ports:
          - name: web
            containerPort: 80
        volumeMounts:
            # name must match the volume name below
            - name: nfs
              mountPath: "/usr/share/nginx/html"
              readOnly: true
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
