apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nfs
    enviroment: development
  name: nfs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Mi
