apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: jenkins
    enviroment: production
    version: v1
  name: jenkins
spec:
  replicas: 1
  selector:
    app: jenkins
    version: v1
  template:
    metadata:
      labels:
        app: jenkins
        enviroment: production
        version: v1
    spec:
      containers:
      - image: jenkins:latest
        name: jenkins
        ports:
        - containerPort: 8080
          name: jenkins-web
        - containerPort: 50000
          name: jenkins-leader
        resources:
          limits:
            cpu: 1000m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
