apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: jenkins
    enviroment: production
    version: v1
  name: jenkins-master
spec:
  replicas: 1
  selector:
    app: jenkins
    role: master
    version: v1
  template:
    metadata:
      labels:
        app: jenkins
        enviroment: production
        role: master
        version: v1
    spec:
      containers:
      - env:
        - name: JENKINS_OPTS
          value: --prefix=/jenkins
        image: jenkins:latest
        name: jenkins
        ports:
        - containerPort: 8080
          name: web
        - containerPort: 50000
          name: leader
        resources:
          limits:
            cpu: 1000m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins
      volumes:
      - name: jenkins
        persistentVolumeClaim:
          claimName: jenkins
