apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: jenkins
    enviroment: production
    version: v1
  name: jenkins-slave
spec:
  replicas: 1
  selector:
    app: jenkins
    role: slave
    version: v1
  template:
    metadata:
      labels:
        app: jenkins
        enviroment: production
        role: slave
        version: v1
    spec:
      containers:
      - command:
        - /usr/local/bin/jenkins-slave.sh
        - -master
        - http://$(JENKINS_MASTER_SERVICE_HOST):$(JENKINS_MASTER_SERVICE_PORT_HTTP)
        - -tunnel
        - $(JENKINS_MASTER_SERVICE_HOST):$(JENKINS_MASTER_SERVICE_PORT_SLAVE)
        - -username
        - jenkins
        - -password
        - jenkins
        - -executors
        - "1"
        env: null
        image: csanchez/jenkins-swarm-slave:2.0-net-tools
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - netstat -tan | grep ESTABLISHED
          initialDelaySeconds: 60
          timeoutSeconds: 1
        name: jenkins-slave
