apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: jenkins
    enviroment: production
    version: v1
  name: jenkins-slave-java
spec:
  replicas: 1
  selector:
    app: jenkins
    role: slave-java
    version: v1
  template:
    metadata:
      labels:
        app: jenkins
        enviroment: production
        role: slave-java
        version: v1
    spec:
      containers:
      - env:
        - name: JENKINS_URL
          value: http://10.103.0.11:8080/jenkins
        - name: JENKINS_TUNNEL
          value: 10.103.0.11:50000
        - name: JENKINS_SECRET
          value: 68fb899217e49533750bd9adbe2999a4974ea098e9ce2834f573f94374e161a1
        - name: JENKINS_NODE
          value: slave-java
        image: bborbe/jenkins-jnlp-slave-java:latest
        name: jenkins-slave-java
        resources:
          limits:
            cpu: 1000m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - mountPath: /home/jenkins
          name: jenkins-slave
      volumes:
      - name: jenkins-slave
        persistentVolumeClaim:
          claimName: jenkins-slave
