apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
    enviroment: production
  name: jenkins-master
spec:
  ports:
  - name: http
    nodePort: 30005
    port: 8080
  - name: slave
    nodePort: 30006
    port: 50000
  selector:
    app: jenkins
    role: master
  type: NodePort
