apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jenkins
    enviroment: production
  name: jenkins-slave
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1000Mi
