apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: jenkins
    enviroment: production
  name: jenkins-slave-golang
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1000Mi
  nfs:
    path: /data/jenkins-slave-golang
    server: 172.16.30.9
