apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: jenkins
    enviroment: production
    version: v1
  name: jenkins-master
spec:
  replicas: 1
  selector:
    app: jenkins
    role: master
    version: v1
  template:
    metadata:
      labels:
        app: jenkins
        enviroment: production
        role: master
        version: v1
    spec:
      containers:
      - env:
        - name: JENKINS_OPTS
          value: --prefix=/jenkins
        - name: JAVA_OPTS
          value: -Djava.awt.headless=true -Xmx200m -Dcom.sun.management.jmxremote= -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false
        image: jenkins:latest
        name: jenkins
        ports:
        - containerPort: 8080
          name: web
        - containerPort: 50000
          name: leader
        resources:
          limits:
            cpu: 1000m
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 250Mi
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-master
      volumes:
      - name: jenkins-master
        persistentVolumeClaim:
          claimName: jenkins-master
