apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: aptly
    enviroment: production
    version: v1
  name: aptly-api
spec:
  replicas: 1
  selector:
    app: aptly
    role: api
    version: v1
  template:
    metadata:
      labels:
        app: aptly
        enviroment: production
        role: api
        version: v1
    spec:
      containers:
      - image: bborbe/aptly-dbcleanup:latest
        name: aptly-api
        ports:
        - containerPort: 3845
          name: aptly-api
        resources:
          limits:
            cpu: 500m
            memory: 75Mi
          requests:
            cpu: 100m
            memory: 25Mi
        volumeMounts:
        - mountPath: /aptly
          name: aptly
      volumes:
      - name: aptly
        persistentVolumeClaim:
          claimName: aptly
