apiVersion: v1
kind: ReplicationController
metadata:
  name: aptly-api
  labels:
    app: aptly
    enviroment: development
spec:
  replicas: 1
  selector:
    app: aptly
    role: api
  template:
    metadata:
      labels:
        app: aptly
        role: api
        enviroment: development
    spec:
      containers:
      - name: aptly-api
        image: bborbe/aptly-api
        ports:
        - containerPort: 3845
        volumeMounts:
            - name: aptly-db
              mountPath: "/aptly/db"
            - name: aptly-public
              mountPath: "/aptly/public"
            - name: aptly-pool
              mountPath: "/aptly/pool"
            - name: aptly-upload
              mountPath: "/aptly/upload"
            - name: aptly-home
              mountPath: "/aptly/home"
      volumes:
      - name: aptly-db
        persistentVolumeClaim:
          claimName: aptly-db
      - name: aptly-upload
        persistentVolumeClaim:
          claimName: aptly-upload
      - name: aptly-pool
        persistentVolumeClaim:
          claimName: aptly-pool
      - name: aptly-public
        persistentVolumeClaim:
          claimName: aptly-public
      - name: aptly-home
        persistentVolumeClaim:
          claimName: aptly-home
