apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: aptly
    enviroment: production
  name: aptly-cleanup
spec:
  replicas: 1
  selector:
    app: aptly
    role: cleanup
  template:
    metadata:
      labels:
        app: aptly
        enviroment: production
        role: cleanup
    spec:
      containers:
      - image: bborbe/aptly-dbcleanup-cron:latest
        name: aptly-cleanup
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
