apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: aptly
    enviroment: production
  name: aptly
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8000Mi
