apiVersion: v1
kind: Service
metadata:
  labels:
    app: aptly
    enviroment: production
  name: aptly-public
spec:
  ports:
  - nodePort: 30084
    port: 80
  selector:
    app: aptly
    role: public
  type: NodePort
