apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: aptly
    enviroment: production
  name: aptly-api
spec:
  replicas: 1
  selector:
    app: aptly
    role: api
  template:
    metadata:
      labels:
        app: aptly
        enviroment: production
        role: api
    spec:
      containers:
      - image: bborbe/aptly-dbcleanup:latest
        resources:
          requests:
            memory: "50Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"
            cpu: "500m"
        name: aptly-api
        ports:
        - containerPort: 3845
          name: aptly-api
        volumeMounts:
        - mountPath: /aptly
          name: aptly
      volumes:
      - name: aptly
        persistentVolumeClaim:
          claimName: aptly
