apiVersion: v1
kind: Service
metadata:
  name: aptly-api
  labels:
    app: aptly
    enviroment: production
spec:
  type: NodePort
  selector:
    app: aptly
    role: api
  ports:
    - port: 3845
      nodePort: 30083
