apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aptly-db
  labels:
    app: aptly
    enviroment: production
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
