apiVersion: v1
kind: Service
metadata:
  name: aptly-api
  labels:
    app: aptly
    enviroment: development
spec:
  type: NodePort
  selector:
    app: aptly-api
  ports:
    - port: 8080
      nodePort: 30083
