apiVersion: v1
kind: Service
metadata:
  labels:
    app: aptly
    enviroment: production
  name: aptly-api
spec:
  ports:
  - nodePort: 30083
    port: 3845
  selector:
    app: aptly
    role: api
  type: NodePort
