apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: aptly
    enviroment: production
    version: v1
  name: aptly-public
spec:
  replicas: 2
  selector:
    app: aptly
    role: public
    version: v1
  template:
    metadata:
      labels:
        app: aptly
        enviroment: production
        role: public
        version: v1
    spec:
      containers:
      - image: jrelva/nginx-autoindex
        name: aptly-public
        ports:
        - containerPort: 80
          name: aptly-public
        resources:
          limits:
            cpu: 250m
            memory: 25Mi
          requests:
            cpu: 10m
            memory: 5Mi
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: aptly-public
          readOnly: true
      volumes:
      - name: aptly-public
        persistentVolumeClaim:
          claimName: aptly-public
