apiVersion: v1
kind: Service
metadata:
  name: aptly-web
  labels:
    app: aptly
    enviroment: development
spec:
  type: NodePort
  selector:
    app: web-frontend
  ports:
    - port: 8080
      nodePort: 30083
