apiVersion: v1
kind: ReplicationController
metadata:
  name: aptly-api
  labels:
    app: aptly
    enviroment: production
spec:
  replicas: 1
  selector:
    app: aptly
    role: api
  template:
    metadata:
      labels:
        app: aptly
        role: api
        enviroment: production
    spec:
      containers:
      - name: aptly-api
        image: bborbe/aptly-dbcleanup:latest
        ports:
        - name: aptly-api
          containerPort: 3845
        volumeMounts:
            - name: aptly
              mountPath: "/aptly"
      volumes:
      - name: aptly
        persistentVolumeClaim:
          claimName: aptly
