apiVersion: v1
kind: Service
metadata:
  labels:
    app: puppetmaster
    enviroment: production
  name: puppetmaster
spec:
  ports:
  - nodePort: 30140
    port: 8140
  selector:
    app: puppetmaster
  type: NodePort
