apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: puppetmaster
    enviroment: production
  name: puppetmaster-ssl
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Mi
  nfs:
    path: /data/puppetmaster-ssl
    server: 172.16.30.9
