apiVersion: v1
kind: Service
metadata: 
  name: puppetmaster
  labels: 
    app: puppetmaster
    enviroment: production
spec:
  type: NodePort
  selector:
    app: puppetmaster
  ports:
    - port: 8140
      nodePort: 30140