apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: puppetmaster
    enviroment: production
  name: puppetmaster-ssl
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
