apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: nfs-server
    enviroment: development
  name: nfs-server
spec:
  replicas: 1
  selector:
    app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
        enviroment: development
    spec:
      containers:
      - image: gcr.io/google_containers/volume-nfs
        resources:
          requests:
            memory: "50Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"
            cpu: "250m"
        name: nfs-server
        ports:
        - containerPort: 2049
          name: nfs-server
        securityContext:
          privileged: true
