apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-server
  labels:
    app: nfs-server
    enviroment: development
spec:
  replicas: 1
  selector:
    app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
        enviroment: development
    spec:
      containers:
      - name: nfs-server
        image: gcr.io/google_containers/volume-nfs
        ports:
          - name: nfs
            containerPort: 2049
        securityContext:
          privileged: true
