apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: nfs-server
    version: v1
    enviroment: development
  name: nfs-server
spec:
  replicas: 1
  selector:
    app: nfs-server
    version: v1
  template:
    metadata:
      labels:
        app: nfs-server
        version: v1
        enviroment: development
    spec:
      containers:
      - image: gcr.io/google_containers/volume-nfs
        name: nfs-server
        ports:
        - containerPort: 2049
          name: nfs-server
        resources:
          limits:
            cpu: 250m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        securityContext:
          privileged: true
