apiVersion: v1
kind: Service
metadata:
  labels:
    app: heapster
    enviroment: production
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: Grafana
  name: monitoring-grafana
  namespace: kube-system
spec:
  ports:
  - name: http
    nodePort: 30007
    port: 80
  selector:
    k8s-app: influxGrafana
  type: NodePort
