apiVersion: v1
kind: Service
metadata:
  labels:
    app: heapster
    enviroment: production
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: Grafana
  name: monitoring-grafana
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - name: web
    port: 3000
    nodePort: 30007
  selector:
    k8s-app: influxGrafana
