apiVersion: v1
kind: Service
metadata:
  labels:
    app: heapster
    enviroment: production
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: Heapster
  name: heapster
  namespace: kube-system
spec:
  ports:
  - nodePort: 30008
    port: 80
    targetPort: 8082
  selector:
    k8s-app: heapster
  type: NodePort
