apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: heapster
    kubernetes.io/cluster-service: "true"
  name: heapster-v1.0.0
  namespace: kube-system
spec:
  replicas: 1
  selector:
    k8s-app: heapster
  template:
    metadata:
      labels:
        k8s-app: heapster
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - command:
        - /heapster
        - --source=kubernetes.summary_api:''
        - --sink=gcm
        - --metric_resolution=60s
        image: gcr.io/google_containers/heapster:v1.0.0
        name: heapster
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ssl-certs
          readOnly: true
      - command:
        - /eventer
        - --source=kubernetes:''
        - --sink=gcl
        image: gcr.io/google_containers/heapster:v1.0.0
        name: eventer
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ssl-certs
          readOnly: true
      volumes:
      - hostPath:
          path: /etc/ssl/certs
        name: ssl-certs
