apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: heapster
    enviroment: production
    k8s-app: heapster
    kubernetes.io/cluster-service: "true"
  name: heapster-v1.0.0
  namespace: kube-system
spec:
  replicas: 1
  selector:
    k8s-app: heapster
  template:
    metadata:
      labels:
        app: heapster
        enviroment: production
        k8s-app: heapster
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - command:
        - /heapster
        - --source=kubernetes.summary_api:''
        - --sink=influxdb:http://monitoring-influxdb:8086
        - --metric_resolution=60s
        image: gcr.io/google_containers/heapster:v1.0.0
        name: heapster
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      - command:
        - /eventer
        - --source=kubernetes:''
        - --sink=influxdb:http://monitoring-influxdb:8086
        image: gcr.io/google_containers/heapster:v1.0.0
        name: eventer
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
