apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: heapster
    enviroment: production
    kubernetes.io/cluster-service: "true"
  name: heapster-influxdb
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1000Mi
