apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: heapster
    enviroment: production
    kubernetes.io/cluster-service: "true"
  name: heapster-influxdb
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1000Mi
  nfs:
    path: /data/heapster-influxdb
    server: 172.16.30.9
