apiVersion: v1
kind: Service
metadata:
  labels:
    app: heapster
    enviroment: production
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: InfluxDB
  name: monitoring-influxdb
  namespace: kube-system
spec:
  ports:
  - name: http
    nodePort: 30010
    port: 8083
    targetPort: 8083
  - name: api
    nodePort: 30009
    port: 8086
    targetPort: 8086
  selector:
    k8s-app: influxGrafana
  type: NodePort
