apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: heapster
    enviroment: production
    k8s-app: influxGrafana
    kubernetes.io/cluster-service: "true"
    version: v2
  name: monitoring-influxdb-grafana-v2
  namespace: kube-system
spec:
  replicas: 1
  selector:
    k8s-app: influxGrafana
    version: v2
  template:
    metadata:
      labels:
        app: heapster
        enviroment: production
        k8s-app: influxGrafana
        kubernetes.io/cluster-service: "true"
        version: v2
    spec:
      containers:
      - image: gcr.io/google_containers/heapster_influxdb:v0.4
        name: influxdb
        ports:
        - containerPort: 8083
          hostPort: 8083
        - containerPort: 8086
          hostPort: 8086
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
        volumeMounts:
        - mountPath: /data
          name: influxdb-persistent-storage
      - env:
        - name: INFLUXDB_SERVICE_URL
          value: http://monitoring-influxdb:8086
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_SERVER_ROOT_URL
          value: /api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/
        image: beta.gcr.io/google_containers/heapster_grafana:v2.1.1
        name: grafana
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /var
          name: grafana-persistent-storage
      volumes:
      - emptyDir: {}
        name: influxdb-persistent-storage
      - emptyDir: {}
        name: grafana-persistent-storage
