apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: postgres
    enviroment: production
    version: v1
  name: postgres
spec:
  replicas: 1
  selector:
    app: postgres
    version: v1
  template:
    metadata:
      labels:
        app: postgres
        enviroment: production
        version: v1
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: 8PfiWhkwZi0NKohD
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: postgres
        image: postgres
        name: postgres
        ports:
        - containerPort: 5432
          name: postgres
        resources:
          limits:
            cpu: 1000m
            memory: 200Mi
          requests:
            cpu: 250m
            memory: 50Mi
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres
      volumes:
      - name: postgres
        persistentVolumeClaim:
          claimName: postgres
