apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: postgres
    enviroment: production
  name: postgres
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 200Mi
  nfs:
    path: /data/postgres
    server: 172.16.30.9
