apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
    enviroment: production
  name: postgres
spec:
  ports:
  - nodePort: 30001
    port: 5432
  selector:
    app: postgres
  type: NodePort
