apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres
    enviroment: production
  name: postgres
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
