apiVersion: v1
kind: Service
metadata: 
  name: static-go-webserver
  labels: 
    app: static-go-webserver
    enviroment: development
spec:
  type: NodePort
  selector:
    app: static-go-webserver
  ports:
    - port: 8080
      nodePort: 30080