apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: minecraft
    enviroment: production
  name: minecraft
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2000Mi
  nfs:
    path: /data/minecraft
    server: 172.16.30.9
