apiVersion: v1
kind: Service
metadata:
  labels:
    app: minecraft
    enviroment: production
  name: minecraft
spec:
  ports:
  - nodePort: 30000
    port: 20000
  selector:
    app: minecraft
  type: NodePort
