apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: minecraft
    enviroment: production
  name: minecraft
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2000Mi
