apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: minecraft
    enviroment: production
  name: minecraft
spec:
  replicas: 1
  selector:
    app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
        enviroment: production
    spec:
      containers:
      - image: bborbe/minecraft:latest
        name: minecraft
        ports:
        - containerPort: 20000
          name: minecraft
        resources:
          limits:
            cpu: 1000m
            memory: 768Mi
          requests:
            cpu: 250m
            memory: 512Mi
        volumeMounts:
        - mountPath: /opt/msm
          name: minecraft
      volumes:
      - name: minecraft
        persistentVolumeClaim:
          claimName: minecraft
