apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: minecraft
    enviroment: production
  name: minecraft
spec:
  replicas: 1
  selector:
    app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
        enviroment: production
    spec:
      containers:
      - image: bborbe/minecraft:latest
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "768Mi"
            cpu: "1000m"
        name: minecraft
        ports:
        - containerPort: 20000
          name: minecraft
        volumeMounts:
        - mountPath: /opt/msm
          name: minecraft
      volumes:
      - name: minecraft
        persistentVolumeClaim:
          claimName: minecraft
