apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: nginx
    enviroment: development
    version: v1
  name: nginx
spec:
  replicas: 2
  selector:
    app: nginx
    version: v1
  template:
    metadata:
      labels:
        app: nginx
        enviroment: development
        version: v1
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: nginx
        resources:
          limits:
            cpu: 250m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
