apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    enviroment: development
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 8080
      nodePort: 30081
