apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    enviroment: development
  name: nginx
spec:
  ports:
  - nodePort: 30081
    port: 8080
  selector:
    app: nginx
  type: NodePort
