apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: nginx
    enviroment: development
  name: nginx
spec:
  replicas: 2
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
        enviroment: development
    spec:
      containers:
      - image: nginx
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
          limits:
            memory: "50Mi"
            cpu: "250m"
        name: nginx
        ports:
        - containerPort: 80
          name: nginx
