apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  labels:
    app: nginx
    enviroment: development
spec:
  replicas: 2
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
        enviroment: development
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
