apiVersion: v1
kind: Pod
metadata:
  name: hello-world-po
spec:  # specification of the pod’s contents
  restartPolicy: Never
  containers:
  - name: hello
    image: "ubuntu:14.04"
    command: ["/bin/echo","Hello World!"]
