apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: backup
    enviroment: production
  name: backup
spec:
  replicas: 1
  selector:
    app: backup
  template:
    metadata:
      labels:
        app: backup
        enviroment: production
    spec:
      containers:
      - image: bborbe/backup-rsync:latest
        name: backup
        ports:
        - containerPort: 22
          name: backup
        resources:
          limits:
            cpu: 1000m
            memory: 200Mi
          requests:
            cpu: 250m
            memory: 100Mi
        volumeMounts:
        - mountPath: /data
          name: backup
          readOnly: true
      volumes:
      - name: backup
        persistentVolumeClaim:
          claimName: backup
