apiVersion: v1
kind: Service
metadata:
  labels:
    app: backup
    enviroment: production
  name: backup
spec:
  ports:
  - nodePort: 30022
    port: 22
  selector:
    app: backup
  type: NodePort
