apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: backup
    enviroment: production
  name: backup
spec:
  replicas: 1
  selector:
    app: backup
  template:
    metadata:
      labels:
        app: backup
        enviroment: production
    spec:
      containers:
      - image: bborbe/backup-rsync:latest
        resources:
          requests:
            memory: "100Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "1000m"
        name: backup
        ports:
        - containerPort: 22
          name: backup
        volumeMounts:
        - mountPath: /data
          name: backup
          readOnly: true
      volumes:
      - name: backup
        persistentVolumeClaim:
          claimName: backup
