apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: backup
    enviroment: production
  name: backup
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8000Mi
